apiVersion: apps/v1
kind: Deployment
metadata:
  name: bilibilipro
spec:
  selector:
    matchLabels:
      app: bilibilipro
  template:
    metadata:
      labels:
        app: bilibilipro
    spec:
      containers:
      - name: bilibilipro
        image: zai7lou/bilibili_tool_pro:2.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 80m
            memory: 100M
          limits:
            cpu: 100m
            memory: 120M
            
  