# 合并main分支后打tag
name: Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    name: add tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get current version
        id: current_version
        run: |
          version=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./common.props)
          echo "Curent version: $version"
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          new_tag="${{ steps.current_version.outputs.current_version }}"
          git tag -f "$new_tag"
          git push -f origin "$new_tag"
